### ISSUE TITLE
Fingerprinted image assets in production

### ISSUE THREAD

**Issue by JackCA** [jakeleboeuf/ember-cli-bodymovin#2]
In a production environment, ember-cli will [fingerprint image assets](https://ember-cli.com/user-guide/#fingerprinting-and-cdn-urls).

It appears that this addon doesn't support passing on the fingerprinted image assets used in a bodymovin animation because bodymovin requests the non-fingerprinted file names.

I have explicitly set the `exclude` option to ignore my `animations` directory and it works now without the fingerprinted filenames, but I wonder if this should happen automatically, or if there's a way to use the fingerprinted image urls themselves.

Thoughts?

**Comment by jakeleboeuf** [comment]
Thanks @JackCA - Looking into a solution for this 👍

**Comment by culpepper** [comment]
Would this prevent the animation from rendering all together? I've installed everything appropriately I believe and upon looking in the inspector, I see the div that was created is empty.

.HBS
```
<div style="margin:100px auto; width: 600px; height: 300px; border: #333 2px solid;">
   {{body-movin path='teamdb_loading_dots' autoplay=true autorender=true }}
</div>
```

Rendered HTML in Inspector
```
<div style="margin:100px auto; width: 600px; height: 300px; border: #333 2px solid;">
   <div id="ember436" class="bodymovin ember-view">
</div>
</div>
```

**Comment by jakeleboeuf** [comment]
Hey @culpepper- is this a production specific issue? Assets will not be fingerprinted in dev, so you're likely running into another issue if this is happening in development. Are you getting any errors in your console?

**Comment by culpepper** [comment]
Thanks for your reply.

No, this isn't running in prod at the moment, I built and ran for development. I'll keep digging though and post back any success. Also no errors at the moment.

**Comment by culpepper** [comment]
OK success!! 

I had to use the "external" property because my directory structure is just different enough to where it wasn't seeing my JSON files. 

`{{body-movin external="true" path="/path_to_my_files/myfiles.json" }}`

All is good now. Thanks for making this addon!!

**Comment by jakeleboeuf** [comment]
Rad, glad you got it working!
